Person.create([
    {
        img:"http://localhost:4000/images/3.JPG",
        fullname:"Doumbia Fode",
        date_naissance:"16/05/1999",
        lieu:"Abobo",
        nationality:"Ivoirienne",
        size:"1m85",
        situation:"Célibataire",
        sexe:"M",
        tel:"0777880082",
        profession:"Etudiant",
        addresse:"Cocody Angre Sicogi",
        email:"fode77doumbia@gmail.com",
        cni:"CNI 078896900",
        passeport:"22AP6789",
        ps_conduite:"DOUM20024457",
        current_status:"R.A.S",
    },
    {
        img:"http://localhost:4000/images/cr7.jpeg",
        fullname:"Cristiano Ronaldo",
        date_naissance:"16/05/1984",
        lieu:"Mader",
        nationality:"Portuguaise",
        size:"1m85",
        situation:"Célibataire",
        sexe:"M",
        tel:"+1 234569989",
        profession:"Footballeur",
        addresse:"",
        email:"cr7@gmail.com",
        cni:"POR088762662",
        passeport:"20AP4389",
        ps_conduite:"CR20024457",
        current_status:"R.A.S",
    },
    {
        img:"http://localhost:4000/images/leo.jpeg",
        fullname:"Leo Messi",
        date_naissance:"16/10/1984",
        lieu:"Bueno aires",
        nationality:"Argentine",
        size:"1m65",
        situation:"Marié avec 4 enfants",
        sexe:"M",
        tel:"+23 234569989",
        profession:"Footballeur",
        addresse:"bueno aires r145",
        email:"leo@gmail.com",
        cni:"ARG088762662",
        passeport:"15LA4389",
        ps_conduite:"LM20024457",
        current_status:"R.A.S",
    },
    {
        img:"http://localhost:4000/images/haaland.jpeg",
        fullname:"Haaland.png",
        date_naissance:"16/08/1997",
        lieu:"Norjaland",
        nationality:"Norvege",
        size:"1m95",
        situation:"Celibataires",
        sexe:"M",
        tel:"+44 234569989",
        profession:"Footballeur",
        addresse:"Norv R198 ",
        email:"haaland@gmail.com",
        cni:"NORV088762662",
        passeport:"10L14389",
        ps_conduite:"EH20024457",
        current_status:"R.A.S",
    },
    
])